#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# RUTAS PARA CONTROLADOR: USUARIO #
user:
    path: /usuario
    controller: App\Controller\UserController::index
    methods: [POST]

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]

# RUTAS PARA CONTROLADOR: VIDEO #
video:
    path: /video
    controller: App\Controller\VideoController::index
